"""Convert financial columns to decimal precision

Revision ID: 3ec56aa29af9
Revises: 
Create Date: 2025-09-14 21:53:46.385452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec56aa29af9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitive_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('estimated_nil_budget', sa.DECIMAL(15,2), nullable=True),
    sa.Column('estimated_revenue_share', sa.DECIMAL(15,2), nullable=True),
    sa.Column('recruiting_wins', sa.Integer(), nullable=True),
    sa.Column('recruiting_losses', sa.Integer(), nullable=True),
    sa.Column('market_share_region', sa.String(), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitive_intelligence_id'), 'competitive_intelligence', ['id'], unique=False)
    op.create_table('report_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('cadence', sa.String(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_schedules_id'), 'report_schedules', ['id'], unique=False)
    op.create_table('social_media_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.DECIMAL(5,4), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('social_nil_value', sa.DECIMAL(15,2), nullable=True),
    sa.Column('measurement_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_metrics_id'), 'social_media_metrics', ['id'], unique=False)
    
    # Convert existing Float columns to DECIMAL for financial precision
    op.alter_column('teams', 'revenue_share_cap',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    op.alter_column('teams', 'current_revenue_share',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    op.alter_column('teams', 'nil_budget',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    
    op.alter_column('athletes', 'sacks',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athletes', 'baron_hopson_score',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athletes', 'market_value',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    op.alter_column('athletes', 'nil_value',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    op.alter_column('athletes', 'revenue_share_value',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    
    op.alter_column('nil_deals', 'deal_value',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    
    op.alter_column('athlete_evaluations', 'performance_score',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'potential_score',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'marketability_score',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'leadership_score',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'academic_score',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'overall_score',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'recommended_nil_value',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'recommended_revenue_share',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    
    op.alter_column('transfer_portal_entries', 'baron_hopson_score_at_entry',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,2),
                   existing_nullable=True)
    op.alter_column('transfer_portal_entries', 'market_value_at_entry',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    
    op.alter_column('revenue_share_allocations', 'allocation_amount',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    op.alter_column('revenue_share_allocations', 'allocation_percentage',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(5,4),
                   existing_nullable=True)
    op.alter_column('revenue_share_allocations', 'back_pay_amount',
                   existing_type=sa.Float(),
                   type_=sa.DECIMAL(15,2),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('revenue_share_allocations', 'back_pay_amount',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('revenue_share_allocations', 'allocation_percentage',
                   existing_type=sa.DECIMAL(5,4),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('revenue_share_allocations', 'allocation_amount',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    
    op.alter_column('transfer_portal_entries', 'market_value_at_entry',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('transfer_portal_entries', 'baron_hopson_score_at_entry',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    
    op.alter_column('athlete_evaluations', 'recommended_revenue_share',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'recommended_nil_value',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'overall_score',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'academic_score',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'leadership_score',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'marketability_score',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'potential_score',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athlete_evaluations', 'performance_score',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    
    op.alter_column('nil_deals', 'deal_value',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    
    op.alter_column('athletes', 'revenue_share_value',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athletes', 'nil_value',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athletes', 'market_value',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athletes', 'baron_hopson_score',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('athletes', 'sacks',
                   existing_type=sa.DECIMAL(5,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    
    op.alter_column('teams', 'nil_budget',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('teams', 'current_revenue_share',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.alter_column('teams', 'revenue_share_cap',
                   existing_type=sa.DECIMAL(15,2),
                   type_=sa.Float(),
                   existing_nullable=True)
    
    op.drop_index(op.f('ix_social_media_metrics_id'), table_name='social_media_metrics')
    op.drop_table('social_media_metrics')
    op.drop_index(op.f('ix_report_schedules_id'), table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index(op.f('ix_competitive_intelligence_id'), table_name='competitive_intelligence')
    op.drop_table('competitive_intelligence')
    # ### end Alembic commands ###
